name: 'Obsidian left'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left"]'
      alphas: '["QWERTY"]'
      extra: '["default"]'
      tap: '["default"]'
      nav: '["default"]'
      clipboard: '["default"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["default"]'
      branches: '["default"]'
      modules: '["default"]'
      kconfig: '["CONFIG_ZMK_KEYBOARD_NAME=\\\"obsidian\\\"\\nCONFIG_ZMK_POINTING=y\\nCONFIG_ZMK_STUDIO=y\\nCONFIG_ZMK_STUDIO_LOCKING=n\\nCONFIG_ZMK_BATTERY_REPORTING=y\\nCONFIG_ZMK_BATTERY_REPORT_INTERVAL=60"]'
