# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build obsidian corne nice_nano qwerty'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left"]'
      alphas: '["QWERTY"]'
      extra: '["default"]'
      tap: '["default"]'
      nav: '["default"]'
      clipboard: '["default"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["default"]'
      kconfig: '["CONFIG_ZMK_KEYBOARD_NAME=\\\"obsidian\\\"","CONFIG_ZMK_POINTING=y","CONFIG_ZMK_STUDIO=y","CONFIG_ZMK_STUDIO_UNLOCK_ALL=y"]'
      branches: '["default"]'
      modules: '["default"]'
